#!/bin/bash
CONFIG=~/.config/fontconfig/fonts.conf
if [ -f ~/.fonts.conf ]; then
               rm ~/.fonts.conf
               cp /usr/share/mmfs/fonts.conf $CONFIG
               echo ".fonts.conf is deprecated. Replaced new config in .config/fontconfig"
       fi

       if [ ! -f $CONFIG ]; then
               mkdir -p ~/.config/fontconfig
               cp /usr/share/mmfs/fonts.conf $CONFIG
               echo "Found no config. Created new."
       fi

declare -a fontList=(	Myanmar3
			Myanmar\ Text
			Noto\ Sans\ Myanmar\ UI
			Noto\ Sans\ Myanmar
			)

CURRENTFONT=""
for i in "${!fontList[@]}"
do
	##check what's the current font in fontconfig
	if grep -q -w "${fontList[$i]}" "$CONFIG"; then
		echo "Found ${fontList[$i]}"
		CURRENTFONT=${fontList[$i]}
		fontList[$i]=true ## update the list
		break
	fi
done


FONT=$(	zenity --list --radiolist --title="Myanmar Font Switcher" --width=400 --height=400 2> /dev/null --text="Choose a system font..." --column="Check:" --column="Font Name:" "${fontList[0]}" "Myanmar3" "${fontList[1]}" "Zawgyi" "${fontList[2]}" "Noto Sans Myanmar ZawDecode" "${fontList[3]}" "Noto Sans Myanmar")

if [[ $FONT ]]; then
	if [[ $FONT = "Zawgyi" ]]; then
		FONT="Myanmar Text"
	fi
	if [[ $FONT = "Noto Sans Myanmar ZawDecode" ]]; then
		FONT="Noto Sans Myanmar UI"
	fi
	sed -i "s/$CURRENTFONT/$FONT/g" $CONFIG
fi
